const leftdetails = [
  {
    name: "UX / UI Designers",
    detail1:
      "Work with us on developing intuitive digital solutions for web, iOS and Android, including VR and AR.",
    detail2: "User experience",
    detail3: "Information architecture",
    detail4: "User interface",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Frame_38_3b01df3060.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Frame_37_358a71da2d.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Frame_35_abbb33857f.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Frame_34_9c16717da3.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Frame_36_730299e1f6.png",
  },
  {
    name: "Cloud Architects",
    detail1:
      "Work with us on developing intuitive digital solutions for web, iOS and Android, including VR and AR.",
    detail2: "Servers and elastic services",
    detail3: "Databases",
    detail4: "Serverless databases, microservices and APIs",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Windows_server_7f7d368713.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Linux_47d7a7048d.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/AWS_4be40bd393.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Google_cloud_38c91b6ee6.png",
  },
  {
    name: "Data Architects",
    detail1:
      "Outsource big data strategy design, development and implementation in the GCP and AWS clouds.",
    detail2: "Extraction",
    detail3: "Storage",
    detail4: "Processing",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Spark_a46ac664bb.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tableau_5481a3cdfc.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/AWS_697e5225c1.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Google_cloud_da150c6032.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Sql_00a7fa1d72.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Nosql_9a50b1b8d2.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Hadhoop_ff0a3ae5d6.png",
    img8: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/python_9e3ab22ce2.png",
  },
  {
    name: "Machine Learning Engineers",
    detail1:
      "Create and train models that drive production software components.",
    detail2: "Machine learning engineering",
    detail3: "Natural language processing",
    detail4: "AI engineering",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/AWS_9d4ee8e4a3.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Open_ai_6383f798d7.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Keras_87b79de0e6.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Anaconda_29bc1e80f8.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/python_ea9417f578.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Chatgtp_feeff48866.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Google_cloud_8802c7aab2.png",
    img8: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tensor_flow_734e6d015e.png",
    img9: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/ptorch_fe6670177d.png",
    img10:
      "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Weka_0318e61396.png",
  },
  {
    name: "Data Scientists",
    detail1:
      "Get deep insights into your data and use them to gain a competitive advantage.",
    detail2: "Cybersecurity analysis",
    detail3: "Data engineering, mining and visualization",
    detail4: "Market and operations data analytics",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Spark_a46ac664bb.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/python_9e3ab22ce2.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Weka_47ebed7643.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tableau_5481a3cdfc.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Hadhoop_ff0a3ae5d6.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Sql_00a7fa1d72.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tensor_flow_cfa2b8f9cc.png",
  },

  {
    name: "Data Engineers",
    detail1:
      "Add experts to your team to extract, transform and store large volumes of data.",
    detail2: "DataOps or data platforms",
    detail3: "Pipeline-focused data engineering",
    detail4: "Analytics-focused data engineering",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Jupyter_d93778700c.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Pandas_7f8e59c35c.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Docker_b9920cbceb.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Excel_b88a005907.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Kaggle_cf3421f638.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Git_3529927c45.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Numpy_55df27a253.png",
  },
  {
    name: "Front-end Developers",
    detail1:
      "Build stunning and user-friendly websites that create digital ecosystem.",
    detail2: "Web design",
    detail3: "Development App design",
    detail4: "Development UI componenttization",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/JS_3abc5aa768.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/React_52596eb1d4.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Astro_88d2178c26.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Next_3446679266.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Angular_f69767cae4.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/CSS_a33b209a45.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tailwind_a9dcf32b5b.png",
    img8: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tamano_personalizado_4_4991d14e36.png",
    img9: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Vite_e042573486.png",
    img10:
      "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Tamano_personalizado_8_02caac36d4.png",
  },

  {
    name: "Back-end Developers",
    detail1: "Build and maintain data storage, security and other functions.",
    detail2: "Software design",
    detail3: "Database modeling",
    detail4: "Software architecture",
    img1: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/AWS_51b75140bc.png",
    img2: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Php_718a4e7e02.png",
    img3: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Serveless_d3637c9b90.png",
    img4: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Strapi_4a352ea388.png",
    img5: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/python_22b64c2baa.png",
    img6: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Java_158ba4f242.png",
    img7: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Wordpress_ea539f61d9.png",
    img8: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Google_cloud_a06344cea8.png",
    img9: "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Node_4f3ff79ffa.png",
    img10:
      "https://code-labs.s3.amazonaws.com/www.code-labs.com/uploads/Nosql_9d4b5526d8.png",
  },
];
export default leftdetails;
